services:
  retrogamer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./src/main/resources/application.properties:/app/application.properties:ro
    environment:
      - SPRING_CONFIG_LOCATION=classpath:/,file:/app/application.properties
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/retrogamer
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root123*
    depends_on:
      database:
        condition: service_healthy

  database:
    image: mysql:8.0
    container_name: mysql-database
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123*
      MYSQL_DATABASE: retrogamer
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
